apiVersion: v1
kind: Pod
metadata:
  name: debug-hostpath
  namespace: devops-hand
spec:
  containers:
  - name: debug
    image: busybox
    command:
      - sh
      - -c
      - "sleep 3600"
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-mount
      mountPath: /mnt
  volumes:
  - name: host-mount
    hostPath:
      path: /mnt
      type: DirectoryOrCreate
  nodeSelector:
    kubernetes.io/hostname: my-cluster-worker2
