apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MTIzCg==  # base64 encoded password
  mysql-database: bXlkYgo=         # base64 encoded database name
  #mysql-user: dXNlcg==                 # base64 encoded username
 # mysql-password: cGFzc3dvcmQ=         # base64 encoded user password
